# Generated by Django 5.2.4 on 2025-07-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='autor',
            field=models.CharField(default='Unknown author', max_length=100),
            preserve_default=False,
        ),
    ]
